### ISSUE TITLE
Receive error UnknownEndpointError: could not resolve endpoint

### ISSUE THREAD

**Issue by fideloper** [jippi/go-metadataproxy#69]
Hi!

I've been pretty successful so far (I think! IAM permissions get crazy!) but I've been banging my head on this one for a bit:

When the proxy attempts to assume a role for a container role, I get a  [UnknownEndpointError  error](https://docs.aws.amazon.com/sdk-for-go/api/aws/endpoints/#UnknownEndpointError). 

This error appears to be related to the Go SDK resolving/creating an API endpoint to hit (vs being related to VPC endpoints which I thought at first...).

Here's the log output from `go-metadataproxy` run via the Docker Hub container (`latest`).

<details>
  <summary>Click to see log output</summary>
<pre>
time="2020-07-06T01:23:10Z" level=info msg="Found container IP '172.17.0.3' in [/pensive_newton] within network 'bridge'" aws.api_version=latest aws.role.requested=my-container-role http.handler=iam-security-crentials-for-role remote_addr=172.17.0.3 request.id=cde12345-1234-1234-1234-123456789000 request.path="/meta-data/iam/security-credentials/{requested_role}"
time="2020-07-06T01:23:10Z" level=info msg="Looking for IAM role for arn:aws:iam::123456789123:role/my-container-role" aws.api_version=latest aws.role.requested=my-container-role container_id=4dd79afa7f5c3ab74541d5b6f0b031a92807f594811b1138a3c01a809fd54d36 http.handler=iam-security-crentials-for-role remote_addr=172.17.0.3 request.id=cde12345-1234-1234-1234-123456789000 request.path="/meta-data/iam/security-credentials/{requested_role}"
time="2020-07-06T01:23:10Z" level=info msg="Found IAM role arn:aws:iam::123456789123:role/my-container-role in cache" aws.api_version=latest aws.cache.role=hit aws.role.requested=my-container-role container_id=4dd79afa7f5c3ab74541d5b6f0b031a92807f594811b1138a3c01a809fd54d36 http.handler=iam-security-crentials-for-role remote_addr=172.17.0.3 request.id=cde12345-1234-1234-1234-123456789000 request.path="/meta-data/iam/security-credentials/{requested_role}"
time="2020-07-06T01:23:10Z" level=info msg="Looking for STS Assume Role for arn:aws:iam::123456789123:role/my-container-role" aws.api_version=latest aws.cache.role=hit aws.role.requested=my-container-role container_id=4dd79afa7f5c3ab74541d5b6f0b031a92807f594811b1138a3c01a809fd54d36 http.handler=iam-security-crentials-for-role remote_addr=172.17.0.3 request.id=cde12345-1234-1234-1234-123456789000 request.path="/meta-data/iam/security-credentials/{requested_role}"
time="2020-07-06T01:23:10Z" level=info msg="Requesting STS Assume Role info for arn:aws:iam::123456789123:role/my-container-role from AWS" aws.api_version=latest aws.cache.assume_role=miss aws.cache.role=hit aws.role.requested=my-container-role container_id=4dd79afa7f5c3ab74541d5b6f0b031a92807f594811b1138a3c01a809fd54d36 http.handler=iam-security-crentials-for-role remote_addr=172.17.0.3 request.id=cde12345-1234-1234-1234-123456789000 request.path="/meta-data/iam/security-credentials/{requested_role}"
time="2020-07-06T01:23:10Z" level=error msg="UnknownEndpointError: could not resolve endpoint\n\tpartition: \"aws\", service: \"sts\", region: \"\", known: [us-east-1-fips us-east-2-fips us-west-2 eu-west-2 sa-east-1 ca-central-1 eu-central-1 eu-north-1 eu-west-3 us-west-1 us-west-1-fips ap-southeast-2 aws-global us-west-2-fips ap-northeast-2 ap-south-1 ap-southeast-1 eu-west-1 me-south-1 us-east-2 ap-east-1 ap-northeast-1 us-east-1]" aws.api_version=latest aws.cache.assume_role=miss aws.cache.role=hit aws.role.requested=my-container-role container_id=4dd79afa7f5c3ab74541d5b6f0b031a92807f594811b1138a3c01a809fd54d36 error.code=could_not_assume_role error.description="UnknownEndpointError: could not resolve endpoint\n\tpartition: \"aws\", service: \"sts\", region: \"\", known: [us-east-1-fips us-east-2-fips us-west-2 eu-west-2 sa-east-1 ca-central-1 eu-central-1 eu-north-1 eu-west-3 us-west-1 us-west-1-fips ap-southeast-2 aws-global us-west-2-fips ap-northeast-2 ap-south-1 ap-southeast-1 eu-west-1 me-south-1 us-east-2 ap-east-1 ap-northeast-1 us-east-1]" http.handler=iam-security-crentials-for-role remote_addr=172.17.0.3 request.id=cde12345-1234-1234-1234-123456789000 request.path="/meta-data/iam/security-credentials/{requested_role}" response.code=404
</pre>
</details>

The interesting part is:

```
msg="UnknownEndpointError: could not resolve endpoint\n\tpartition: \"aws\", service: \"sts\", region: \"\", known: [us-east-1-fips us-east-2-fips us-west-2 eu-west-2 sa-east-1 ca-central-1 eu-central-1 eu-north-1 eu-west-3 us-west-1 us-west-1-fips ap-southeast-2 aws-global us-west-2-fips ap-northeast-2 ap-south-1 ap-southeast-1 eu-west-1 me-south-1 us-east-2 ap-east-1 ap-northeast-1 us-east-1]"
```

Looking at the code in this project, the error appears to be returned when calling [`sts.AssumeRole`](https://github.com/jippi/go-metadataproxy/blob/master/internal/aws.go#L129-L131).

I can make the same request on the same host machine successfully using the `aws` command:

```bash
aws sts assume-role --role-arn arn:aws:iam::123456789123:role/my-container-role --role-session-name fideloper
```

The container in question gets the full ARN for the `IAM_ROLE` environment variable (just as is passed to the `--role-arn` flag above).

**Have you seen that error from the Golang SDK before?**

**Comment by jippi** [comment]
Have you explicitly set the `AWS_REGION` in your Nomad job? Looks like its resolving the region to `""` based on your error line. The Go SDK doesn't resolve the region by default, so have to be provided. I guess it works locally due to your `~/.aws/config` file :)

**Comment by fideloper** [comment]
That feels very obvious, and worked haha

```
    env {
        ENABLE_PROMETHEUS = "true"
        AWS_DEFAULT_REGION = "us-east-2"
      }
```

What tripped me up was that the `aws sts assume-role...` command was run on the server with Nomad, which doesn't have any region information setup there, although that could be a difference between python/Go SDK's or maybe something the CLI does to guess the region.

Thanks for all your help! I believe I finally got this all setup. The docs on the 2-tier IAM setup were 💯
